import React, { useState } from "react";
import {
  View,
  Text,
  TextInput,
  StyleSheet,
  ScrollView,
  Alert,
  TouchableOpacity,
} from "react-native";
import { DarkModeStatus } from "../../app/useStore";
import { Colors, getDarkTheme, getLightTheme } from "../../utils/colors";

export default function TermScreen({ navigation }) {
  const mode = DarkModeStatus();
  return (
    <View
      style={[
        styles.page,
        {
          backgroundColor: mode
            ? getDarkTheme.backgroundColor
            : getLightTheme.backgroundColor,
        },
      ]}
    >
      <View style={{ width: "100%" }}>
        <ScrollView
          showsVerticalScrollIndicator={false}
          contentContainerStyle={{
            padding: 10,
            paddingBottom: 50,
            width: "100%",
          }}
        >
          <View style={{ width: "100%" }}>
            <Text style={styles.heading}>Acceptance of the Terms of Use </Text>
            <Text
              style={{ color: mode ? getDarkTheme.color : getLightTheme.color }}
            >
              These terms of use are entered into by and between You and
              Playwise of of PW Esports Private Limited (“Playwise”, ”Company”,
              “We”, “Our”, or “Us”). The following terms and conditions,
              together with any documents they expressly incorporate by
              reference (collectively, “Terms of Use”), govern your access to
              and use of https://Playwise.gg (the “Website” the term website
              includes Playwise mobile Application), including any content,
              functionality, and services offered on or through the Website
              whether as a guest or a registered user. Such Terms of Use
              constitute a binding agreement between you (hereinafter "you" or
              “your") and Playwise. Please read the Terms of Use carefully
              before you start to use the Website. By using this Website and
              submitting your personal data to its database, you agree to be
              bound by these Terms of Use and that Playwise may process your
              personal information for the purposes described in these Terms of
              Use and consistent with the Website’s Privacy Policy. If you do
              not want to agree to these Terms of Use or the Privacy Policy you
              must not access or use the Website. By accessing the Website and,
              installing or using our Application you represent that you are
              competent to enter into this contract under the laws of India and
              further signify your agreement to be bound by the Terms of Use. We
              grant such users a non-transferrable, limited, non-exclusive and
              revocable privilege to register an Account on and use the Website
              or Application. These Terms of Use constitute an 'electronic
              record' within the meaning of the laws of India (including the
              Information Technology Act, 2000) and are generated by a computer
              system and do not require any physical or digital signatures.
              These Terms have been published in accordance with the provisions
              of Rule 3(1) of the Information Technology (Intermediary
              Guidelines) Rules, 2011. By using the services, you agree to
              contract electronically with us and agree to these Terms of Use,
              together with any documents that maybe expressly referred to and
              are incorporated by reference herein, including our Privacy
              Policy. You agree that these electronic terms combined with your
              act of using the Website or Application, have the same force and
              effect as your written signature and satisfy any laws that require
              a writing or signature. You shall not use the services if you: (a)
              do not agree to these Terms of Use; (b) are not of the age of 18
              years; or (c) are prohibited from accessing or using the Website
              or Application or any of its contents, products or services by
              applicable law. 1. Eligibility This Website and Application must
              only be used or accessed by individuals who are competent to enter
              into a legally binding contract under the Indian Contract Act,
              1872, are individuals who are resident in India (as per the Indian
              tax laws) and are not body corporate. If you are a minor (i.e. you
              are under the age of 18 years), you must not use the Application
              or Website. No person who is involved in the development of the
              Application and/or Services can participate in any Games, where
              such participation could alter, modify or unduly influence his/her
              performance on the Game, without our express written permission
              and subject to such terms and conditions as we may seek to impose
              on such person. Certain Games being provided on the Application
              may be subject to additional conditions or rules applicable to
              that particular Game, including in the form of questionnaires/FAQs
              ("Game Terms"). Such Game Terms are deemed to be incorporated
              herein by reference. Users must agree and adhere to these Game
              Terms before playing any such Game on the Application. To the
              extent that these Terms are inconsistent with Game Terms, the Game
              Terms shall prevail. We reserve the right to terminate your
              Account and/or deny access to the Website or Application if it is
              brought to our notice that you have violated the Terms or Privacy
              Policy or applicable law. 2. State Restrictions Any user residing
              in the states of Assam, Odisha, Nagaland, Sikkim, Andhra Pradesh,
              Meghalaya and Telangana and any other state as notified by the
              central/state government/ court ruling in India from time to time
              ("Restricted States") are prohibited from participating in any
              Games on the Website or Application. It is hereby clarified that
              some of the Restricted States such as Meghalaya and Nagaland have
              requirements where games of skill for stakes may only be offered
              upon obtaining relevant licenses. Accordingly, at present the
              Games and the services available on the Application are open only
              to persons currently residing in India and who are not residents
              of any of the Restricted States. If you access the Service or any
              Game from any of the Restricted States, you shall be entirely
              liable for any legal or penal consequences and we shall be
              entitled to terminate your account and/or freeze/forfeit the
              balance in your Account on the Website or Application. You must
              note that all Games available on the Website or Application are
              games where your success or/and performance depends predominantly
              upon their superior knowledge, training, attention, experience and
              adroitness ("Games of Skill") in playing the game and less on
              chance. Each game will reward certain skills, such as knowledge of
              the game, familiarity with rules, experience, reflexes, practice,
              hand-eye coordination etc. ‘Games of Skill’, under Indian law, are
              excluded from the ambit of gambling legislations including, the
              Public Gambling Act of 1867 and other state enactments. Given the
              above background, the individuals residing in the Restricted
              States should not participate in Games offered on the Website or
              Application. Any participation by such individuals shall be at
              their sole risk and discretion and we shall not be liable to
              refund or reimburse any injury or damages suffered by such
              individuals. We reserve the right to monitor all activities from
              your Account on the Website or Application to ensure compliance
              with law. If you participate in any Games in violation of any
              central and/or state law(s) in India, we reserve the right to
              cooperate with law enforcement agencies of the relevant state and
              report such participation or/and suspicious activity along with
              all your relevant details. We do not support, endorse or offer
              ‘games of chance’ for money. Each Game that is available on the
              Website or Application has clearly defined rules. You are
              encouraged to read, understand and follow these rules to be
              successful in these Games. We shall not be liable if you do not
              adhere to the Game rules or otherwise engage in gambling or
              betting activities on the Website or Application, which shall
              solely be at your sole risk. 3. Changes to the Terms of Use
              Playwise may revise and update these Terms of Use from time to
              time in its sole discretion. All changes are effective immediately
              when we post them. Your continued use of the Website following the
              posting of revised Terms of Use means that you accept and agree to
              the changes. You are expected to check this page from time to time
              so you are aware of any changes, as they are binding on you. 4.
              Accessing the Website and Account Security Playwise reserves the
              right to withdraw or amend this Website, and any service or
              material Playwise provides on the Website, in our sole discretion
              without notice. Playwise will not be liable if for any reason all
              or any part of the Website is unavailable at any time or for any
              period. From time to time, we may restrict access to some parts of
              the Website, or the entire Website, to users, including registered
              users. You agree and acknowledge to play Games on the Website or
              Application at your own risk and we shall not be held liable for
              any loss of winning amount or any technical difficulties faced by
              you. You are also urged to keep a stable internet connection
              throughout the game to ensure minimum glitches. You are
              responsible for making all arrangements necessary for you to have
              access to the Website. To access the Website or some of the
              resources it offers, you may be asked to provide certain
              registration details or other information. It is a condition of
              your use of the Website that all the information you provide on
              the Website is correct, current, and complete. You agree that all
              information you provide to register with this Website or
              otherwise, including, but not limited to, through the use of any
              interactive features on the Website, is governed by our Privacy
              Policy, and you consent to all actions we take with respect to
              your information consistent with our Privacy Policy. If you
              choose, or are provided with, a user name, password, or any other
              piece of information as part of our security procedures, you must
              treat such information as confidential, and you must not disclose
              it to any other person or entity. You also acknowledge that your
              account is personal to you and agree not to provide any other
              person with access to this Website or portions of it using your
              user name, password, or other security information. You agree to
              notify us immediately of any unauthorized access to or use of your
              user name or password or any other breach of security. You also
              agree to ensure that you exit from your account at the end of each
              session. You should use particular caution when accessing your
              account from a public or shared computer so that others are not
              able to view or record your password or other personal
              information. We have the right to disable any user name, password,
              or other identifier, whether chosen by you or provided by us, at
              any time in our sole discretion for any or no reason, including
              if, in our opinion, you have violated any provision of these Terms
              of Use 5. Intellectual Property Rights The Website and its entire
              contents, features, and functionality (including but not limited
              to all information, software, text, displays, images, video, and
              audio, and the design, selection, and arrangement thereof) are
              owned by Playwise, its licensors, or other providers of such
              material and are protected by copyright, trademark, patent, trade
              secret, and other intellectual property or proprietary rights
              laws. These Terms of Use permit you to use the Website for your
              personal, non-commercial use only. You must not reproduce,
              distribute, modify, create derivative works of, publicly display,
              publicly perform, republish, download, store, or transmit any of
              the material on our Website. You must not: • Modify copies of any
              materials from this site. • Use any illustrations, photographs,
              video or audio sequences, or any graphics separately from the
              accompanying text. • Delete or alter any copyright, trademark, or
              other proprietary rights notices from copies of materials from
              this site. You must not access or use for any commercial purposes
              any part of the Website or any services or materials available
              through the Website. If you print, copy, modify, download, or
              otherwise use or provide any other person with access to any part
              of the Website in breach of the Terms of Use, your right to use
              the Website will stop immediately and you must, at our option,
              return or destroy any copies of the materials you have made. No
              right, title, or interest in or to the Website or any content on
              the Website is transferred to you, and all rights not expressly
              granted are reserved by the Company. Any use of the Website not
              expressly permitted by these Terms of Use is a breach of these
              Terms of Use and may violate copyright, trademark, and other laws.
              Notwithstanding anything to the contrary herein, you acknowledge
              and agree that you shall have no ownership or other interest in
              your Account, and further acknowledge and agree that all rights in
              and to your Account are and shall forever be owned by and inure to
              our benefit.You also acknowledge and accept that we cannot
              guarantee the authenticity of any data which users may provide
              about themselves. You acknowledge that all contents accessed by
              you while using the Website is at your own risk and you will be
              sole responsible for any damage or loss to any party resulting
              therefrom. 6. Trademarks Playwise’s name, logo, and all related
              names, logos, product and service names, designs, and slogans are
              trademarks of Playwise or its affiliates or licensors. You must
              not use such marks without the prior written permission of
              Playwise. All other names, logos, product and service names,
              designs, and slogans on this Website are the trademarks of their
              respective owners. 7. Prohibited uses You may use the Website only
              for lawful purposes and in accordance with these Terms of Use. You
              agree not to use the Website: • In any way that violates any
              applicable national, state, local, or international law or
              regulation. • For the purpose of exploiting, harming, or
              attempting to exploit or harm minors in any way by exposing them
              to inappropriate content, asking for personally identifiable
              information, or otherwise. • To send, knowingly receive, upload,
              download, use, or re-use any material that does not comply with
              the Content Standards set out in these Terms of Use. • To
              transmit, or procure the sending of, any advertising or
              promotional material, including any “junk mail,” “chain letter,”
              “spam,” or any other similar solicitation. • To impersonate or
              attempt to impersonate Playwise, an Playwise employee, another
              user, or any other person or entity (including, without
              limitation, by using email addresses or screen names associated
              with any of the foregoing). • To engage in any other conduct that
              restricts or inhibits anyone’s use or enjoyment of the Website, or
              which, as determined by us, may harm Playwise or users of the
              Website, or expose them to liability. Additionally, you agree not
              to: • Use the Website in any manner that could disable,
              overburden, damage, or impair the Website or interfere with any
              other party’s use of the Website, including their ability to
              engage in real time activities through the Website. • Use any
              robot, spider, or other automatic device, process, or means to
              access the Website for any purpose, including monitoring or
              copying any of the material on the Website. • Use any manual
              process to monitor or copy any of the material on the Website, or
              for any other purpose not expressly authorized in these Terms of
              Use, without our prior written consent. • Use any device,
              software, or routine that interferes with the proper working of
              the Website. • Introduce any viruses, Trojan horses, worms, logic
              bombs, or other material that is malicious or technologically
              harmful. • Attempt to gain unauthorized access to, interfere with,
              damage, or disrupt any parts of the Website, the server on which
              the Website is stored, or any server, computer, or database
              connected to the Website. • Attack the Website via a
              denial-of-service attack or a distributed denial-of-service
              attack. • Otherwise attempt to interfere with the proper working
              of the Website. 8. User Contributions The Website may contain
              message boards, chat rooms, personal web pages or profiles,
              forums, bulletin boards, and other interactive features
              (collectively, “Interactive Services”) that allow users to post,
              submit, publish, display, or transmit to other users or other
              persons (hereinafter, “post”) content or materials (collectively,
              “User Contributions”) on or through the Website. All User
              Contributions must comply with the Content Standards set out in
              these Terms of Use. Any User Contribution you post to the site
              will be considered non-confidential and non-proprietary. By
              providing any User Contribution on the Website, you grant us and
              our affiliates and service providers, and each of their and our
              respective licensees, successors, and assigns the right to use,
              reproduce, modify, perform, display, distribute, or otherwise
              disclose to third parties any such material for any purpose, and
              agree that you are not entitled to payment or reimbursement for
              your User Contributions from Playwise or its affiliates. You
              represent and warrant that: • You own or control all rights in and
              to the User Contributions and have the right to grant the license
              granted above to us and our affiliates and service providers, and
              each of their and our respective licensees, successors, and
              assigns. • All of your User Contributions do and will comply with
              these Terms of Use. You understand and acknowledge that you are
              responsible for any User Contributions you submit or contribute,
              and you, not the Company, have full responsibility for such
              content, including its legality, reliability, accuracy, and
              appropriateness. We are not responsible or liable to any third
              party for the content or accuracy of any User Contributions posted
              by you or any other user of the Website. 9. Monitoring and
              Enforcement; Termination Playwise has the right to: • Remove or
              refuse to post any User Contributions for any or no reason in our
              sole discretion. • Take any action with respect to any User
              Contribution that we deem necessary or appropriate in our sole
              discretion, including if we believe that such User Contribution
              violates the Terms of Use, including the Content Standards,
              infringes any intellectual property right or other right of any
              person or entity, threatens the personal safety of users of the
              Website or the public, or could create liability for the Company.
              • Disclose your identity or other information about you to any
              third party who claims that material posted by you violates their
              rights, including their intellectual property rights or their
              right to privacy. • Take appropriate legal action, including
              without limitation, referral to law enforcement, for any illegal
              or unauthorized use of the Website. • Terminate or suspend your
              access to all or part of the Website for any or no reason,
              including without limitation, any violation of these Terms of Use.
              Without limiting the foregoing, we have the right to cooperate
              fully with any law enforcement authorities or court order
              requesting or directing us to disclose the identity or other
              information of anyone posting any materials on or through the
              Website. YOU WAIVE AND HOLD HARMLESS Playwise AND ITS AFFILIATES,
              LICENSEES, AND SERVICE PROVIDERS FROM ANY CLAIMS RESULTING FROM
              ANY ACTION TAKEN BY ANY OF THE FOREGOING PARTIES DURING, OR TAKEN
              AS A CONSEQUENCE OF, INVESTIGATIONS BY EITHER SUCH PARTIES OR LAW
              ENFORCEMENT AUTHORITIES. However, Playwise cannot review all
              material before it is posted on the Website, and cannot ensure
              prompt removal of objectionable material after it has been posted.
              Accordingly, Playwise assumes no liability for any action or
              inaction regarding transmissions, communications, or content
              provided by any user or third party. Playwise has no liability or
              responsibility to anyone for performance or nonperformance of the
              activities described in this section. 10.Content Standards These
              content standards apply to any and all User Contributions and use
              of Interactive Services. User Contributions must in their entirety
              comply with all applicable national, state, and international laws
              and regulations. Without limiting the foregoing, User
              Contributions must not: • Contain any material that is defamatory,
              obscene, indecent, abusive, offensive, harassing, violent,
              hateful, inflammatory, or otherwise objectionable. • Promote
              sexually explicit or pornographic material, violence, or
              discrimination based on race, sex, religion, nationality,
              disability, sexual orientation, or age. • Infringe any patent,
              trademark, trade secret, copyright, or other intellectual property
              or other rights of any other person. • Violate the legal rights
              (including the rights of publicity and privacy) of others or
              contain any material that could give rise to any civil or criminal
              liability under applicable laws or regulations or that otherwise
              may be in conflict with these Terms of Use and our Privacy Policy.
              • Be likely to deceive any person. • Promote any illegal activity,
              or advocate, promote, or assist any unlawful act. • Cause
              annoyance, inconvenience, or needless anxiety or be likely to
              upset, embarrass, alarm, or annoy any other person. • Impersonate
              any person, or misrepresent your identity or affiliation with any
              person or organization. • Involve commercial activities or sales,
              such as contests, sweepstakes, and other sales promotions, barter,
              or advertising. • Give the impression that they emanate from or
              are endorsed by us or any other person or entity, if this is not
              the case. 11. Copyright Infringement If you believe in good faith
              that any content displayed or transmitted through the Website
              infringes your copyright, you may reach us at support@playwise.gg
              . 12. Reliance on Information Posted The information presented on
              or through the Website is made available solely for general
              information purposes. Playwise does not warrant the accuracy,
              completeness, or usefulness of this information. Any reliance you
              place on such information is strictly at your own risk. We
              disclaim all liability and responsibility arising from any
              reliance placed on such materials by you or any other visitor to
              the Website, or by anyone who may be informed of any of its
              contents. This Website may include content provided by third
              parties, including materials provided by other users, bloggers,
              and third party licensors, syndicators, aggregators, and/or
              reporting services. All statements and/or opinions expressed in
              these materials, and all articles and responses to questions and
              other content, other than the content provided by Playwise, are
              solely the opinions and the responsibility of the person or entity
              providing those materials. These materials do not necessarily
              reflect the opinion of Playwise. Playwise is not responsible, or
              liable to you or any third party, for the content or accuracy of
              any materials provided by any third parties. 13. Community
              Guidelines We want our Website and Application to be a safe and
              fun place to play online. To facilitate this, we have established
              the following guidelines for participation in the community
              (“Community Guidelines”). These Community Guidelines apply to your
              each and every interaction on our Website and Application, social
              media avenues including but not limited to your interactions with
              our customer support team. You may NOT post content that is in
              relation to any of the following: Threats, Violence{" &"} harm •
              Threatens any person, and which is a threat of violence, physical
              or mental harm. • Promotes or encourages suicide or any other type
              of self-injury, including self mutilation. • Promotes
              discrimination, hatred against any individual or group • Includes
              nudity, gruesome crime or accident scenes, gory media related to
              death, serious injury, violence, or surgical procedures. • Content
              that is gratuitously shocking, sadistic, or excessively graphic,
              including with respect to animals. Impersonation, spam {"&"}{" "}
              hacking • Impersonates another person or entity in a manner that
              does or is intended to mislead, confuse, or deceive others. •
              Publishes or posts links to malicious content intended to damage
              or disrupt another person’s browser or computer. • Uses platform
              for obtaining sensitive personal information, banking and credit
              card details, passwords etc. • Threatens to expose someone’s
              private information or threaten to hack or break into someone’s
              digital information. • Is harassing, abusive, or constitutes spam.
              Harassment {"&"} Bullying • Is directed to an individual,
              including: profiles or posts that identify and shame individuals;
              images altered to degrade individuals; or photos or videos of
              physical bullying posted to shame the victim of such bullying. •
              Attacks a person or group on the basis of attributes such as race,
              religion, ethnic origin, sexual orientation, disability, or
              gender. • Depicts physical or psychological abuse involving
              minors. Sexually Explicit Content, violence • Includes sexual
              harassment, sexual assault threats, sharing intimate material
              without consent, recording or distributing images of sexual
              assaults, cyber stalking, digital dating abuse and luring sexual
              trafficking victims. • Promotes or depicts violence towards
              children, including posting sexually explicit images/videos of
              children. Breach of Third Party Rights • Violates the rights of a
              third party, including copyright, trademark, privacy, and
              publicity rights. Hate Speech {"&"} false information • Is
              defamatory, obscene or pornographic. • Is furtherance of illegal
              activities. • Is intended to deceive or mislead any of other(s)
              and endangers our trust-based community. Terrorism {"&"} Illegal
              Activities • Promotes any organization which is engaged in
              terrorist activity, incites violence against others or organised
              criminal activity. • Seeks to use Hike Sticker Chat for
              furtherance of any illegal activity or any activity that is in
              breach of Community Guidelines. • Disrespects national symbols,
              including national flag and national emblem. • Offers the
              purchase, sale, or trade of unlawfully acquired goods. • Offers,
              sells, trades, or solicits firearms, accessories, ammunition,
              explosive weapons, or instructions on how to manufacture them If
              you do not agree with our Community Guidelines, you may delete
              your Account and/or not access, download and use the Application
              and/or the Services. In the event you wish to report any breach of
              our Community Guidelines, you may contact us at{" "}
              {"<support@playwise.gg>"}. We will review these reports to
              determine whetherthere is a violation of these guidelines and
              determine if any action needs to be taken, at oursole discretion.
              Changes to Community Guidelines: Any changes in the Community
              Guidelines shall be posted on our website to reflect changes in
              the guidelines. You should periodically review Community
              Guidelines for the latest information on our community guidelines.
              Once posted, those changes are effective immediately. Continued
              access or use of the Application and/or the Services constitutes
              your acceptance of the changes and the amended Community
              Guidelines. Please take these guidelines seriously and honour them
              in the spirit in which they are intended. We’ll do our best to
              enforce them consistently and fairly. We reserve the right at all
              times (but will not have an obligation) to take down any content
              in breach of our Terms or Community Guidelines and to take any
              other actions as we deem fit including, suspending Users or
              reclaiming usernames without liability to you. 14. Changes to the
              Website Playwise may update the content on this Website from time
              to time, but its content is not necessarily complete or
              up-to-date. Any of the material on the Website may be out of date
              at any given time, and Playwise is under no obligation to update
              such material. 15. Privacy Policy Please read our Privacy Policy
              to understand our practices which govern your use of the Website.
              Any information (including your personal information and/or
              sensitive personal data or information) provided by you on the
              Website will be collected, stored, processed, transferred or
              shared by us and our affiliates in accordance with our Privacy
              Policy. These Terms are deemed to incorporate the Privacy Policy
              in its entirety. 16. Linking to the Website and Social Media
              Features You may link to our homepage, provided you do so in a way
              that is fair and legal and does not damage our reputation or take
              advantage of it, but you must not establish a link in such a way
              as to suggest any form of association, approval, or endorsement on
              our part. The Website may provide certain social media features
              that enable you to: • Link from your own or certain third-party
              websites to certain content on this Website. • Send emails or
              other communications with certain content, or links to certain
              content, on this Website. • Cause limited portions of content on
              this Website to be displayed or appear to be displayed on your own
              or certain third-party websites. You may use these features solely
              as they are provided by us, and solely with respect to the content
              they are displayed with, and otherwise in accordance with any
              additional terms and conditions we provide with respect to such
              features. Subject to the foregoing, you must not: • Establish a
              link from any website that is not owned by you. • Cause the
              Website or portions of it to be displayed on, or appear to be
              displayed by, any other site, for example, framing, deep linking,
              or in-line linking. • Link to any part of the Website other than
              the homepage. • Otherwise take any action with respect to the
              materials on this Website that is inconsistent with any other
              provision of these Terms of Use. The website from which you are
              linking, or on which you make certain content accessible, must
              comply in all respects with the Content Standards set out in these
              Terms of Use. You agree to cooperate with us in causing any
              unauthorized framing or linking immediately to stop. We reserve
              the right to withdraw linking permission without notice. We may
              disable all or any social media features and any links at any time
              without notice in our discretion. 17. Links to Third Party
              Sites/Services The Website may contain links to other websites and
              resources provided by third parties, these links are provided for
              your convenience only. This includes links contained in
              advertisements, including banner advertisements and sponsored
              links. We have no control over the contents of those sites or
              resources, and accept no responsibility for them or for any loss
              or damage that may arise from your use of them. If you decide to
              access any of the third-party websites linked to this Website, you
              do so entirely at your own risk and subject to the terms and
              conditions of use for such websites. Certain services available on
              the Website are delivered by third party sites and organizations.
              By using any product, service or functionality originating from
              the Website, you hereby acknowledge and consent that Playwise may
              share such information and data with any third party with whom
              Playwise has a contractual relationship to provide the requested
              product, service or functionality on behalf of Playwise users. The
              third party’s collection, use, and disclosure of your information
              will be subject to that third-party service’s privacy notice. 18.
              Disclaimer of Warranties You understand that Playwise cannot and
              does not guarantee or warrant that files available for downloading
              from the internet or the Website will be free of viruses or other
              destructive code. You are responsible for implementing sufficient
              procedures and checkpoints to satisfy your particular requirements
              for anti-virus protection and accuracy of data input and output,
              and for maintaining a means external to our site for any
              reconstruction of any lost data. TO THE FULLEST EXTENT PROVIDED BY
              LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A
              DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER
              TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER
              EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL
              DUE TO YOUR USE OF THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED
              THROUGH THE WEBSITE OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED
              ON IT, OR ON ANY WEBSITE LINKED TO IT. YOUR USE OF THE WEBSITE,
              ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE
              WEBSITE IS AT YOUR OWN RISK. THE WEBSITE, ITS CONTENT, AND ANY
              SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE ARE PROVIDED ON AN
              “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OF ANY
              KIND, EITHER EXPRESS OR IMPLIED. NEITHER THE COMPANY NOR ANY
              PERSON ASSOCIATED WITH THE COMPANY MAKES ANY WARRANTY OR
              REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY,
              RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE WEBSITE.
              WITHOUT LIMITING THE FOREGOING, NEITHER PLAYWISE NOR ANYONE
              ASSOCIATED WITH PLAYWISE REPRESENTS OR WARRANTS THAT THE WEBSITE,
              ITS CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE
              WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT
              DEFECTS WILL BE CORRECTED, THAT OUR SITE OR THE SERVER THAT MAKES
              IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR
              THAT THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE
              WEBSITE WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS. TO THE
              FULLEST EXTENT PROVIDED BY LAW, PLAYWISE HEREBY DISCLAIMS ALL
              WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR
              OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
              MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR
              PURPOSE. Additionally, the contents provided through the Website
              may include technical inaccuracies or typographical errors. We may
              make changes or improvements to the website at any time. The
              contents or any information available on the Website is without
              warranties of any kind either expressed or implied, to the fullest
              extent permissible pursuant to applicable laws, including but not
              limited to: • any implied warranty or merchantability, fitness for
              a particular purpose; • hat the contents of the Website will be
              uninterrupted or error-free; • the defects, if any on the Website
              will be corrected; • any harm resulting from downloading or
              accessing any information or material, the quality of servers,
              games, products, Application, Services or sites, cancellation of
              competition and prizes. • the Website being constantly available
              or available at all; • installation or uninstallation choices in
              relation to the Website being successfully executed in all cases;
              • Your personal ability to use the Website; • Your satisfaction
              with the use of the Website; • that Website will meet your
              requirements and expectations; • the accuracy of the data provided
              by the Website; • the security and privacy of Your data; • that
              all bugs or errors in relation to the Website will be corrected; •
              that the Website will be compatible with all devices and all
              networks; • that the Website is fit for a particular purpose or
              use; • that the Website and the contents thereof are accessible in
              every location; or • that the Website and the contents would be
              perpetually secure and not prone to breaches of security anywhere
              in the world. 19. Limitation on Liability TO THE FULLEST EXTENT
              PROVIDED BY LAW, IN NO EVENT WILL THE COLLECTIVE LIABILITY OF
              PLAYWISE AND ITS SUBSIDIARIES AND AFFILIATES, AND THEIR LICENSORS,
              SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, AND DIRECTORS, TO
              ANY PARTY (REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT,
              TORT, OR OTHERWISE) EXCEED THE GREATER OF INDIAN RUPEES FIFTY ONLY
              (INR. 50/-). THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT
              CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. You shall
              access the Playwise website provided on Playwise voluntarily and
              at their own risk. Playwise shall, under no circumstances be held
              responsible or liable on account of any loss or damage sustained
              (including but not limited to any accident, injury, death, loss of
              property) by You or any other person or entity during the course
              of access to the Playwise website (including participation in the
              contest(s)/ tournament etc) or as a result of acceptance of any
              prize. Playwise accepts no liability, whether jointly or
              severally, for any errors or omissions, whether on behalf of
              itself or third parties in relation to the prizes. 20.
              Indemnification You agree to defend, indemnify, and hold harmless
              Playwise, its affiliates, licensors, and service providers, and
              its and their respective officers, directors, employees,
              contractors, agents, licensors, suppliers, successors, and assigns
              from and against any claims, liabilities, damages, judgments,
              awards, losses, costs, expenses, or fees (including reasonable
              attorneys’ fees) arising out of or relating to your violation of
              these Terms of Use or your use of the Website, including, but not
              limited to, your User Contributions, any use of the Website’s
              content, services, and products other than as expressly authorized
              in these Terms of Use, or your use of any information obtained
              from the Website. Additionally, You shall be solely responsible
              for any consequences which may arise due to their access of
              Playwise website by conducting an illegal act or due to
              non-conformity with these Terms and Conditions and other rules and
              regulations in relation to Playwise website, including provision
              of incorrect address or other personal details. You also undertake
              to indemnify Playwise and their respective officers, directors,
              employees and agents on the happening of such an event (including
              without limitation cost of attorney, legal charges etc.) on full
              indemnity basis for any loss/damage suffered by Playwise on
              account of such act on your part. You shall indemnify, defend, and
              hold Playwise harmless from any third party/entity/ organization
              claims arising from or related to such User's engagement with the
              Playwise or participation in any Contest. In no event shall
              Playwise be liable to You for acts or omissions arising out of or
              related to User's engagement with the Playwise or his/her
              participation in any Contest(s). In consideration of Playwise
              allowing You to access the Playwise website, to the maximum extent
              permitted by law, You waive and release each and every right or
              claim, all actions, causes of actions (present or future) each of
              them has or may have against Playwise, its respective agents,
              directors, officers, business associates, group companies,
              sponsors, employees, or representatives for all and any injuries,
              accidents, or mishaps (whether known or unknown) or (whether
              anticipated or unanticipated) arising out of the provision of
              Playwise website or related to the Contests or the prizes of the
              Contests. 21. Disclaimers • To the extent permitted under law,
              neither Playwise nor its parent/holding company, subsidiaries,
              affiliates, directors, officers, professional advisors, employees
              shall be responsible for the deletion, the failure to store, the
              mis-delivery, or the untimely delivery of any information or
              material. • To the extent permitted under law, Playwise shall not
              be responsible for any harm resulting from downloading or
              accessing any information or material, the quality of servers,
              games, products, Playwise Services or sites, cancellation of
              competition and prizes. Playwise disclaims any responsibility for,
              and if You pay for access to one of Playwise's Services, You will
              not be entitled to a refund as a result of, any inaccessibility
              that is caused by Playwise's maintenance on the servers or the
              technology that underlies our sites, failures of Playwise's
              service providers (including telecommunications, hosting, and
              power providers), computer viruses, natural disasters or other
              destruction or damage of our facilities, acts of nature, war,
              civil disturbance, or any other cause beyond our reasonable
              control. In addition, Playwise does not provide any warranty as to
              the content on the Playwise website. Playwise’s content is
              distributed on an "as is, as available" basis. • Any material
              accessed, downloaded or otherwise obtained through Playwise is
              done at the Your discretion, competence, acceptance and risk, and
              You will be solely responsible for any potential damage to Your
              computer system or loss of data that results from a Your download
              of any such material. • In case Playwise discovers any error,
              including any error in the determination of Winners or in the
              transfer of amounts to Your account, Playwise reserves the right
              (exercisable at its discretion) to rectify the error in such
              manner as it deems fit, including through a set-off of the
              erroneous payment from amounts due to the User or deduction from
              Your account of the amount of erroneous payment. In case of
              exercise of remedies in accordance with this clause, Playwise
              agrees to notify to You of the error and of the exercise of the
              remedy(ies) to rectify the same. • To the extent permitted under
              law, neither Playwise nor its partners, licensors or associates
              shall be liable for any direct, indirect, incidental, special, or
              consequential damages arising out of the use of or inability to
              use our sites, even if we have been advised of the possibility of
              such damages. • Any Playwise service, events or Contest(s) being
              hosted or provided, or intended to be hosted on Playwise platform
              and requiring specific permission or authority from any statutory
              authority or any state or the central government, or the board of
              directors shall be deemed cancelled or terminated, if such
              permission or authority is either not obtained or denied either
              before or after the availability of the relevant Playwise service,
              events or Contest(s) are hosted or provided. • To the extent
              permitted under law, in the event of suspension or closure of any
              services, events or Contests, Users (including Participants) shall
              not be entitled to make any demands, claims, on any nature
              whatsoever. 22.Force Majeure We will not be liable to you for any
              eventuality caused directly or indirectly as a result of using the
              Website, in case of any Force Majeure Event. A Force Majeure Event
              is defined as any act of God, wars or threat of war (declared or
              undeclared), insurrections, acts of terrorism, epidemic, pandemic,
              governments actions (including but not limited to passage of any
              law, order), lockouts, civil unrest, demonstrations, real or
              potential labour disputes, any natural disaster, inability to
              obtain relevant authorisations or accident or defect in
              telecommunication network or any other act, affecting our ability
              to offer Services and which are beyond our reasonable control.
              Force Majeure Event may render it difficult or impossible for us
              to continue to provide the Services on its Website or Application
              and we retain the right to suspend, limit or terminate the Website
              until further notice. 23.Communications We may communicate with
              you through email, SMS, telephone, by posting notifications on the
              Website or Application (including push notifications) or any other
              means of communication. By using the Website, you consent to
              receive such communications from us including in relation to the
              Website or Services, your account information or any updates/
              changes to the Website and/ or other promotional or marketing
              communications from us. We may allow you to use the Services to
              initiate SMS or text messages or other online communication to
              your friends, family, or other contacts. You are not required to
              send such text messages, however in case you do then you shall be
              solely responsible for them. You understand that standard text
              messaging and data rates may apply based on your plan with your
              mobile phone carrier. You also understand that we do not control
              the recipients, content, or timing of these text messages. If you
              choose to send any messages through the Services, you represent
              and warrant to us that the recipients of the messages have
              appropriately consented to receive the messages. If you intend to
              participate in a promotion, and have listed your phone numbers on
              the National Do Not Call Registry (“NDNC Registry”), then you
              shall deregister the same from the NDNC Registry till the
              completion of such promotion. You agree not to make any claim or
              raise any complaint whatsoever against us in this respect. Please
              note that persons intending to participate in a promotion who have
              not de-registered themselves from the NDNC Registry shall also
              have no right to make any claim or raise any complaints against us
              if they do or do not receive any call or SMS with respect to their
              participation and all other matters pertaining to a promotion.
              24.Governing Law All matters relating to the Website and these
              Terms of Use, and any dispute or claim arising therefrom or
              related thereto (in each case, including non-contractual disputes
              or claims), shall be governed and construed in accordance with the
              laws of India. 25.Jurisdiction You waive any and all objections to
              the exercise of jurisdiction and consents to the exclusive
              jurisdiction of courts located in the Sate of Rajasthan in any
              action arising out of or relating to legal suit, action, or
              proceeding arising out of, or related to, these Terms of Use or
              the Website. 26.Refunds and Disputes of Charges To dispute a
              charge or request a refund, please e-mail s support@playwise.gg
              Refunds and disputes will be handled on a case-by-case basis at
              Playwise’s sole discretion. 27.Dispute Resolution The courts of
              competent jurisdiction at Rajasthan shall have exclusive
              jurisdiction to determine any and all disputes arising out of, or
              in connection with, the Application or the Services provided by
              us, the construction, validity, interpretation and enforceability
              of these Terms of Use, or your or our rights and obligations, as
              well as the exclusive jurisdiction to grant interim or preliminary
              relief in case of any dispute referred to arbitration as given
              below. In the event of any legal dispute (which may be a legal
              issue or question) which may arise, firstly the party raising the
              dispute shall provide a written notification ("Notification") to
              the other party. On receipt of Notification, the parties shall
              first try to resolve the dispute through discussions. In the event
              that the parties are unable to resolve the dispute within fifteen
              (15) days of receipt of Notification, the dispute shall be settled
              by arbitration. The place of arbitration shall be Jaipur,
              Rajasthan, India by a sole arbitrator who shall be appointed by us
              and whose decision shall be final and binding upon all the
              parties. All arbitration proceedings shall be conducted in English
              and in accordance with the provisions of the Arbitration and
              Conciliation Act, 1996, as amended from time to time. Nothing
              contained in these Terms of Use shall prevent us from seeking and
              obtaining interim or permanent equitable or injunctive relief, or
              any other relief available to safeguard our interest prior to,
              during or following the filing of arbitration proceedings or
              pending the execution of a decision or award in connection with
              any arbitration proceedings from any court having jurisdiction to
              grant the same. The pursuit of equitable or injunctive relief
              shall not constitute a waiver on our part to pursue any remedy for
              monetary damages through the arbitration described herein.
              28.Limitation on Time to File Claims ANY CAUSE OF ACTION OR CLAIM
              YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF USE OR
              THE WEBSITE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE
              OF ACTION ACCRUES; OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS
              PERMANENTLY BARRED. 29.Waiver and Severability No waiver by
              Playwise of any term or condition set out in these Terms of Use
              shall be deemed a further or continuing waiver of such term or
              condition or a waiver of any other term or condition, and any
              failure of Playwise to assert a right or provision under these
              Terms of Use shall not constitute a waiver of such right or
              provision. If any provision of these Terms of Use is held by a
              court or other tribunal of competent jurisdiction to be invalid,
              illegal, or unenforceable for any reason, such provision shall be
              eliminated or limited to the minimum extent such that the
              remaining provisions of the Terms of Use will continue in full
              force and effect. 30.Entire Agreement The Terms of Use, our
              Privacy Policy, and Copyright Policy constitute the sole and
              entire agreement between you and Playwise regarding the Website
              and supersede all prior and contemporaneous understandings,
              agreements, representations, and warranties, both written and
              oral, regarding the Website. 31. Grievance Officer In the event
              you have any complaints or grievances regarding usage of
              Application or its Services, please contact support at{" "}
              {"<support@playwise.gg> "}who is our Grievance Officer and
              Compliance Officer. The complaints will be redressed in the manner
              provided under the Information Technology Act, 2000, the Consumer
              Protection Act, 2019 and rules framed thereunder. We will
              acknowledge the receipt of any consumer complaint within
              twenty-four hours and redresses the complaint within 15 days from
              the date of receipt of the complaint. 32.Customer Support In case
              where you have any queries pertaining to the Website or
              Application or its Services or the Terms of Use, you may contact
              our customer service at{"<support@playwise.gg >"}.
            </Text>
          </View>
        </ScrollView>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  page: {
    flex: 1,
    paddingHorizontal: 15,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  heading: {
    textAlign: "left",
    fontSize: 18,
    fontWeight: "500",
    color: Colors.primary,
    marginVertical: 20,
  },
  body: {
    fontSize: 14,
    color: "grey",
    marginBottom: 20,
  },
});
